# Generated by Django 3.1.1 on 2020-09-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asvzevent',
            name='beginner_friendly',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
